// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Reqnroll.UI.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class CrearReservaUIFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("es"), "Features", "Crear Reserva UI", "  Como recepcionista del hotel\r\n  Quiero crear una reserva a través de la interfa" +
                "z web\r\n  Para gestionar las reservas de los huéspedes de forma visual", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "CrearReservaUI.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 7
  #line hidden
#line 8
    await testRunner.GivenAsync("que la aplicación web está en ejecución", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 9
    await testRunner.AndAsync("que existen datos de prueba en el sistema", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/CrearReservaUI.feature.ndjson", 5);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Crear reserva exitosa con una habitación")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Crear reserva exitosa con una habitación")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Crear Reserva UI")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ui")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("happy-path")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Empresa Sol", "Pendiente", "102A", "2025-12-15", "2025-12-18", "Jorge Quispe", "0", null, DisplayName="Crear reserva exitosa con una habitación(Empresa Sol,Pendiente,102A,2025-12-15,20" +
            "25-12-18,Jorge Quispe,0)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Agencia Andes", "Pendiente", "103A", "2025-12-20", "2025-12-23", "Andrea Mamani", "1", null, DisplayName="Crear reserva exitosa con una habitación(Agencia Andes,Pendiente,103A,2025-12-20," +
            "2025-12-23,Andrea Mamani,1)")]
        public async global::System.Threading.Tasks.Task CrearReservaExitosaConUnaHabitacion(string cliente, string estado, string habitacion, string fechaEntrada, string fechaSalida, string huesped, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ui",
                    "happy-path"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Cliente", cliente);
            argumentsOfScenario.Add("Estado", estado);
            argumentsOfScenario.Add("Habitacion", habitacion);
            argumentsOfScenario.Add("FechaEntrada", fechaEntrada);
            argumentsOfScenario.Add("FechaSalida", fechaSalida);
            argumentsOfScenario.Add("Huesped", huesped);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Crear reserva exitosa con una habitación", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 12
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 13
    await testRunner.GivenAsync("que navego a la página de nueva reserva", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 14
    await testRunner.WhenAsync(string.Format("selecciono el cliente \"{0}\"", cliente), ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 15
    await testRunner.AndAsync(string.Format("selecciono el estado de reserva \"{0}\"", estado), ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 16
    await testRunner.AndAsync("avanzo al paso de habitaciones", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 17
    await testRunner.AndAsync(string.Format("selecciono la habitación \"{0}\"", habitacion), ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 18
    await testRunner.AndAsync(string.Format("ingreso la fecha de entrada \"{0}\"", fechaEntrada), ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 19
    await testRunner.AndAsync(string.Format("ingreso la fecha de salida \"{0}\"", fechaSalida), ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 20
    await testRunner.AndAsync(string.Format("agrego el huésped \"{0}\"", huesped), ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 21
    await testRunner.AndAsync("confirmo la reserva", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 22
    await testRunner.ThenAsync("debería ver un mensaje de éxito", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 23
    await testRunner.AndAsync("debería ver el ID de la reserva creada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Crear reserva con múltiples habitaciones")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Crear reserva con múltiples habitaciones")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Crear Reserva UI")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ui")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("happy-path")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("multiple-rooms")]
        public async global::System.Threading.Tasks.Task CrearReservaConMultiplesHabitaciones()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "happy-path",
                    "multiple-rooms"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Crear reserva con múltiples habitaciones", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 31
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
  await this.FeatureBackgroundAsync();
#line hidden
#line 32
    await testRunner.GivenAsync("que navego a la página de nueva reserva", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 33
    await testRunner.WhenAsync("selecciono el cliente \"Agencia Andes\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 34
    await testRunner.AndAsync("selecciono el estado de reserva \"Pendiente\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 35
    await testRunner.AndAsync("avanzo al paso de habitaciones", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 36
    await testRunner.AndAsync("selecciono la habitación \"103A\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 37
    await testRunner.AndAsync("ingreso la fecha de entrada \"2025-12-25\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 38
    await testRunner.AndAsync("ingreso la fecha de salida \"2025-12-28\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 39
    await testRunner.AndAsync("selecciono el huésped \"Jorge Quispe\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 40
    await testRunner.AndAsync("hago click en agregar otra habitación", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 41
    await testRunner.AndAsync("selecciono la segunda habitación \"104A\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 42
    await testRunner.AndAsync("ingreso la segunda fecha de entrada \"2025-12-26\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 43
    await testRunner.AndAsync("ingreso la segunda fecha de salida \"2025-12-29\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 44
    await testRunner.AndAsync("selecciono el segundo huésped \"Diego Rojas\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 45
    await testRunner.AndAsync("avanzo al paso de confirmación", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 46
    await testRunner.AndAsync("confirmo la reserva", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 47
    await testRunner.ThenAsync("debería ver un mensaje de éxito", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 48
    await testRunner.AndAsync("debería ver el ID de la reserva creada", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
