// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Reqnroll.UI.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class GestionDeHabitacionesUIFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = new string[] {
                "ui",
                "habitaciones"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("es"), "Features", "Gestión de Habitaciones UI", "  Como administrador del hotel\r\n  Quiero gestionar las habitaciones (CRUD) bajo e" +
                "l patrón POM\r\n  Para validar el sistema con datos de Pairwise y Happy Path", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "GestionHabitacionesUI.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 8
  #line hidden
#line 9
    await testRunner.GivenAsync("que la aplicación web está en ejecución", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 10
    await testRunner.AndAsync("que navego a la página de listado de habitaciones", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/GestionHabitacionesUI.feature.ndjson", 9);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("HP01 - Insertar nuevas habitaciones usando Pairwise")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("HP01 - Insertar nuevas habitaciones usando Pairwise")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Gestión de Habitaciones UI")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ui")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("habitaciones")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("insert")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("pairwise")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("H-01", "701A", "1", "Suite", "0", null, DisplayName="HP01 - Insertar nuevas habitaciones usando Pairwise(H-01,701A,1,Suite,0)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("H-02", "502A", "1", "Simple", "1", null, DisplayName="HP01 - Insertar nuevas habitaciones usando Pairwise(H-02,502A,1,Simple,1)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("H-03", "801B", "2", "Doble", "2", null, DisplayName="HP01 - Insertar nuevas habitaciones usando Pairwise(H-03,801B,2,Doble,2)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("H-04", "301D", "3", "Familiar", "3", null, DisplayName="HP01 - Insertar nuevas habitaciones usando Pairwise(H-04,301D,3,Familiar,3)")]
        public async global::System.Threading.Tasks.Task HP01_InsertarNuevasHabitacionesUsandoPairwise(string tC_ID, string numero, string piso, string tipo, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "insert",
                    "pairwise"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("TC_ID", tC_ID);
            argumentsOfScenario.Add("Numero", numero);
            argumentsOfScenario.Add("Piso", piso);
            argumentsOfScenario.Add("Tipo", tipo);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("HP01 - Insertar nuevas habitaciones usando Pairwise", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 13
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 14
    await testRunner.WhenAsync("hago click en el botón \"Nueva Habitación\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 15
    await testRunner.AndAsync(string.Format("ingreso el número de habitación \"{0}\"", numero), ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 16
    await testRunner.AndAsync(string.Format("ingreso el piso \"{0}\"", piso), ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 17
    await testRunner.AndAsync(string.Format("selecciono el tipo de habitación \"{0}\"", tipo), ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 18
    await testRunner.AndAsync("selecciono el estado \"Disponible\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 19
    await testRunner.AndAsync("guardo la habitación", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 20
    await testRunner.ThenAsync(string.Format("debería ver la habitación \"{0}\" en la lista", numero), ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
#line 21
    await testRunner.AndAsync("el mensaje de éxito debería ser visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("HP02 - Consultar una habitación existente")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("HP02 - Consultar una habitación existente")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Gestión de Habitaciones UI")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ui")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("habitaciones")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("select")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("happy-path")]
        public async global::System.Threading.Tasks.Task HP02_ConsultarUnaHabitacionExistente()
        {
            string[] tagsOfScenario = new string[] {
                    "select",
                    "happy-path"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("HP02 - Consultar una habitación existente", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 31
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 32
    await testRunner.WhenAsync("busco la habitación \"102A\" en la lista", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 33
    await testRunner.ThenAsync("debería ver la habitación \"102A\" en la lista", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("HP03 - Actualizar estado de habitación usando Pairwise")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("HP03 - Actualizar estado de habitación usando Pairwise")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Gestión de Habitaciones UI")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ui")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("habitaciones")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("update")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("pairwise")]
        public async global::System.Threading.Tasks.Task HP03_ActualizarEstadoDeHabitacionUsandoPairwise()
        {
            string[] tagsOfScenario = new string[] {
                    "update",
                    "pairwise"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("HP03 - Actualizar estado de habitación usando Pairwise", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 36
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 37
    await testRunner.GivenAsync("que busco la habitación \"101A\" en la lista", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 38
    await testRunner.WhenAsync("hago click en el botón \"Editar\" de la habitación \"101A\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 39
    await testRunner.AndAsync("selecciono el tipo de habitación \"Simple\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 40
    await testRunner.AndAsync("cambio el estado a \"Fuera de Servicio\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 41
    await testRunner.AndAsync("guardo los cambios", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 42
    await testRunner.ThenAsync("el estado de la habitación \"101A\" debería ser \"Fuera de Servicio\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("HP04 - Eliminar una habitación existente")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("HP04 - Eliminar una habitación existente")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Gestión de Habitaciones UI")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ui")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("habitaciones")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("delete")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("happy-path")]
        public async global::System.Threading.Tasks.Task HP04_EliminarUnaHabitacionExistente()
        {
            string[] tagsOfScenario = new string[] {
                    "delete",
                    "happy-path"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("HP04 - Eliminar una habitación existente", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 45
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 8
  await this.FeatureBackgroundAsync();
#line hidden
#line 46
    await testRunner.GivenAsync("que busco la habitación \"301C\" en la lista", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 47
    await testRunner.WhenAsync("elimino la habitación \"301C\" y confirmo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 48
    await testRunner.ThenAsync("la habitación \"301C\" ya no debería aparecer en la lista", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
