// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Reqnroll.UI.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class GestionDeClientesUIFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("es"), "Features", "Gestión de Clientes UI", "    Como administrador del sistema\r\n    Quiero registrar nuevos clientes\r\n    Par" +
                "a poder realizar reservas a su nombre", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "GestionClientesUI.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/GestionClientesUI.feature.ndjson", 12);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Insertar nuevo cliente con datos variados (Pairwise)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Insertar nuevo cliente con datos variados (Pairwise)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Gestión de Clientes UI")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UI")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Insert")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Limites Minimos", "ABC", "1234567", "a@b.co", "0", null, DisplayName="Insertar nuevo cliente con datos variados (Pairwise)(Limites Minimos,ABC,1234567," +
            "a@b.co,0)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Limites Maximos", "Empresa Veinte Letra", "12345678901234567890", "1234567890123456789@correo.com", "1", null, DisplayName="Insertar nuevo cliente con datos variados (Pairwise)(Limites Maximos,Empresa Vein" +
            "te Letra,12345678901234567890,1234567890123456789@correo.com,1)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("RS Max / NIT Min", "Industrias Del Sur O", "7654321", "info@tuhotel.com", "2", null, DisplayName="Insertar nuevo cliente con datos variados (Pairwise)(RS Max / NIT Min,Industrias " +
            "Del Sur O,7654321,info@tuhotel.com,2)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("RS Min / NIT Max", "SOL", "99999999999999999999", "reservas@web.bo", "3", null, DisplayName="Insertar nuevo cliente con datos variados (Pairwise)(RS Min / NIT Max,SOL,9999999" +
            "9999999999999,reservas@web.bo,3)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Valores Tipicos", "Hotel Central", "4578120", "contacto@hotel.com", "4", null, DisplayName="Insertar nuevo cliente con datos variados (Pairwise)(Valores Tipicos,Hotel Centra" +
            "l,4578120,contacto@hotel.com,4)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Email Maximo Exacto", "Cliente Normal", "88776655", "un.cliente.largo@dominio.co.bo", "5", null, DisplayName="Insertar nuevo cliente con datos variados (Pairwise)(Email Maximo Exacto,Cliente " +
            "Normal,88776655,un.cliente.largo@dominio.co.bo,5)")]
        public async global::System.Threading.Tasks.Task InsertarNuevoClienteConDatosVariadosPairwise(string descripcionCasos, string razonSocial, string nIT, string email, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "UI",
                    "Insert"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Descripcion Casos", descripcionCasos);
            argumentsOfScenario.Add("RazonSocial", razonSocial);
            argumentsOfScenario.Add("NIT", nIT);
            argumentsOfScenario.Add("Email", email);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Insertar nuevo cliente con datos variados (Pairwise)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 8
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
    await testRunner.GivenAsync("que estoy en la página de creación de clientes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 10
    await testRunner.WhenAsync(string.Format("ingreso la Razón Social \"{0}\"", razonSocial), ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 11
    await testRunner.AndAsync(string.Format("ingreso el NIT \"{0}\"", nIT), ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 12
    await testRunner.AndAsync(string.Format("ingreso el Email \"{0}\"", email), ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 13
    await testRunner.AndAsync("hago click en guardar cliente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 14
    await testRunner.ThenAsync("debería ver un mensaje de éxito indicando que se guardó correctamente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Crear un cliente nuevo y verificar su visualización en el listado")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Crear un cliente nuevo y verificar su visualización en el listado")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Gestión de Clientes UI")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UI")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Select")]
        public async global::System.Threading.Tasks.Task CrearUnClienteNuevoYVerificarSuVisualizacionEnElListado()
        {
            string[] tagsOfScenario = new string[] {
                    "UI",
                    "Select"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Crear un cliente nuevo y verificar su visualización en el listado", "", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 39
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 41
    await testRunner.GivenAsync("que estoy en la página de creación de clientes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 42
    await testRunner.WhenAsync("ingreso la Razón Social \"Cliente Auto Test\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 43
    await testRunner.AndAsync("ingreso el NIT \"99887766\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 44
    await testRunner.AndAsync("ingreso el Email \"auto.test@hotel.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 45
    await testRunner.AndAsync("hago click en guardar cliente", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 51
    await testRunner.GivenAsync("que navego a la página de listado de clientes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 52
    await testRunner.WhenAsync("busco el cliente por Razón Social \"Cliente Auto Test\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 53
    await testRunner.ThenAsync("debería ver en la grilla al cliente con Razón Social \"Cliente Auto Test\", NIT \"99" +
                        "887766\" y Email \"auto.test@hotel.com\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Editar un cliente existente desde la ventana modal (Pairwise)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Editar un cliente existente desde la ventana modal (Pairwise)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Gestión de Clientes UI")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UI")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Update")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Update Frontera Cruzada 1", "Empresa Modificada X", "1112223", "actualizacion.limite@correo.bo", "7", null, DisplayName="Editar un cliente existente desde la ventana modal (Pairwise)(Update Frontera Cru" +
            "zada 1,Empresa Modificada X,1112223,actualizacion.limite@correo.bo,7)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("Update Frontera Cruzada 2", "UPD", "99999999999999999999", "nuevo@min.com", "8", null, DisplayName="Editar un cliente existente desde la ventana modal (Pairwise)(Update Frontera Cru" +
            "zada 2,UPD,99999999999999999999,nuevo@min.com,8)")]
        public async global::System.Threading.Tasks.Task EditarUnClienteExistenteDesdeLaVentanaModalPairwise(string descripcionCasos, string razonSocial, string nIT, string email, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "UI",
                    "Update"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Descripcion Casos", descripcionCasos);
            argumentsOfScenario.Add("RazonSocial", razonSocial);
            argumentsOfScenario.Add("NIT", nIT);
            argumentsOfScenario.Add("Email", email);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Editar un cliente existente desde la ventana modal (Pairwise)", "", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 58
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 62
    await testRunner.GivenAsync("que existe un cliente registrado con Razón Social \"Cliente Base Edicion\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 63
    await testRunner.AndAsync("navego a la página de listado de clientes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 65
    await testRunner.WhenAsync("busco el cliente \"Cliente Base Edicion\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 66
    await testRunner.AndAsync("hago click en el boton editar del cliente encontrado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 69
    await testRunner.AndAsync(string.Format("actualizo la Razón Social a \"{0}\"", razonSocial), ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 71
    await testRunner.AndAsync(string.Format("actualizo el Email a \"{0}\"", email), ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 72
    await testRunner.AndAsync("guardo los cambios de la edicion", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 74
    await testRunner.ThenAsync(string.Format("debería ver los datos actualizados: Razón Social \"{0}\", NIT \"{1}\" y Email \"{2}\"", razonSocial, nIT, email), ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Eliminar un cliente existente desde el listado")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Eliminar un cliente existente desde el listado")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Gestión de Clientes UI")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("UI")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("Delete")]
        public async global::System.Threading.Tasks.Task EliminarUnClienteExistenteDesdeElListado()
        {
            string[] tagsOfScenario = new string[] {
                    "UI",
                    "Delete"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Eliminar un cliente existente desde el listado", "", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 86
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 88
    await testRunner.GivenAsync("que existe un cliente registrado para eliminar con Razón Social \"Cliente A Borrar" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 89
    await testRunner.AndAsync("navego a la página de listado de clientes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 91
    await testRunner.WhenAsync("busco el cliente \"Cliente A Borrar\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 92
    await testRunner.AndAsync("hago click en el boton eliminar del cliente encontrado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 93
    await testRunner.AndAsync("confirmo la eliminación en la ventana modal", ((string)(null)), ((global::Reqnroll.Table)(null)), "Y ");
#line hidden
#line 95
    await testRunner.ThenAsync("el cliente \"Cliente A Borrar\" ya no debería aparecer en el listado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
