// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Reqnroll.UI.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class HabitacionesUIFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Habitaciones UI", "  Como recepcionista\r\n  Quiero gestionar habitaciones a través de la interfaz web" +
                "\r\n  Para mantener el inventario de habitaciones", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "HabitacionesCRUD.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/HabitacionesCRUD.feature.ndjson", 11);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Crear habitación (Insert) - pruebas pairwise")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Crear habitación (Insert) - pruebas pairwise")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Habitaciones UI")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ui")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("habitaciones")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("insert")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("pairwise")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("101A", "Simple", "100.00", "0", null, DisplayName="Crear habitación (Insert) - pruebas pairwise(101A,Simple,100.00,0)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("102A", "Doble", "0.00", "1", null, DisplayName="Crear habitación (Insert) - pruebas pairwise(102A,Doble,0.00,1)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("103A", "Suite", "9999.99", "2", null, DisplayName="Crear habitación (Insert) - pruebas pairwise(103A,Suite,9999.99,2)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("104A", "Simple", "-1.00", "3", null, DisplayName="Crear habitación (Insert) - pruebas pairwise(104A,Simple,-1.00,3)")]
        public async global::System.Threading.Tasks.Task CrearHabitacionInsert_PruebasPairwise(string numero, string tipoHabitacion, string tarifa, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ui",
                    "habitaciones",
                    "insert",
                    "pairwise"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Numero", numero);
            argumentsOfScenario.Add("TipoHabitacion", tipoHabitacion);
            argumentsOfScenario.Add("Tarifa", tarifa);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Crear habitación (Insert) - pruebas pairwise", @"    Dado que navego a la página de habitaciones
    Cuando ingreso el número de habitación ""<Numero>""
    Y selecciono el tipo ""<TipoHabitacion>""
    Y ingreso la tarifa ""<Tarifa>""
    Y hago click en guardar habitación
    Entonces debería ver un mensaje de éxito
    Y debería ver el ID de la habitación creada", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Actualizar habitación (Update) - pruebas pairwise")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Actualizar habitación (Update) - pruebas pairwise")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Habitaciones UI")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ui")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("habitaciones")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("update")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("pairwise")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("101A", "120.00", "4", null, DisplayName="Actualizar habitación (Update) - pruebas pairwise(101A,120.00,4)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("102A", "0.00", "5", null, DisplayName="Actualizar habitación (Update) - pruebas pairwise(102A,0.00,5)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("103A", "1500.50", "6", null, DisplayName="Actualizar habitación (Update) - pruebas pairwise(103A,1500.50,6)")]
        public async global::System.Threading.Tasks.Task ActualizarHabitacionUpdate_PruebasPairwise(string numeroBusqueda, string nuevaTarifa, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ui",
                    "habitaciones",
                    "update",
                    "pairwise"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("NumeroBusqueda", numeroBusqueda);
            argumentsOfScenario.Add("NuevaTarifa", nuevaTarifa);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Actualizar habitación (Update) - pruebas pairwise", @"    Dado que navego a la página de habitaciones
    Y busco la habitación ""<NumeroBusqueda>""
    Y hago click en editar habitación
    Y modifico la tarifa a ""<NuevaTarifa>""
    Y hago click en guardar cambios
    Entonces debería ver un mensaje de éxito", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 28
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Eliminar habitación existente (Happy Path)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Eliminar habitación existente (Happy Path)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Habitaciones UI")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ui")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("habitaciones")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("delete")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("happy-path")]
        public async global::System.Threading.Tasks.Task EliminarHabitacionExistenteHappyPath()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "habitaciones",
                    "delete",
                    "happy-path"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Eliminar habitación existente (Happy Path)", "    Dado que navego a la página de habitaciones\r\n    Cuando busco la habitación \"" +
                    "101A\"\r\n    Y hago click en eliminar habitación\r\n    Y confirmo la eliminación\r\n " +
                    "   Entonces debería ver un mensaje de confirmación de eliminación", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 43
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Buscar/Seleccionar habitación (Happy Path)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Buscar/Seleccionar habitación (Happy Path)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Habitaciones UI")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ui")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("habitaciones")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("select")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("happy-path")]
        public async global::System.Threading.Tasks.Task BuscarSeleccionarHabitacionHappyPath()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "habitaciones",
                    "select",
                    "happy-path"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Buscar/Seleccionar habitación (Happy Path)", "    Dado que navego a la página de habitaciones\r\n    Cuando busco la habitación \"" +
                    "101A\"\r\n    Entonces debería ver la habitación en la lista", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 51
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
