// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Reqnroll.UI.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class HuespedesUIFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Huéspedes UI", "  Como recepcionista\r\n  Quiero gestionar huéspedes a través de la interfaz web\r\n " +
                " Para mantener el catálogo de huéspedes", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "HuespedesUI.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute(Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupBehavior.EndOfClass)]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/HuespedesUI.feature.ndjson", 14);
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Crear huésped (Insert) - datos pairwise")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Crear huésped (Insert) - datos pairwise")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Huéspedes UI")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ui")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("huesped")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("insert")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("pairwise")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("HU-P1", "Jorge", "", "Quispe", "Flores", "CI200001", "70011111", "1985-03-10", "0", null, DisplayName="Crear huésped (Insert) - datos pairwise(HU-P1,Jorge,,Quispe,Flores,CI200001,70011" +
            "111,1985-03-10,0)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("HU-P2", "A", "Luis", "Quispe", "", "P1234567", "", "1992-07-25", "1", null, DisplayName="Crear huésped (Insert) - datos pairwise(HU-P2,A,Luis,Quispe,,P1234567,,1992-07-25" +
            ",1)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("HU-P3", "NombreMuyLargoExceso", "", "Quispe", "García", "CI0", "123", "2000-09-09", "2", null, DisplayName="Crear huésped (Insert) - datos pairwise(HU-P3,NombreMuyLargoExceso,,Quispe,García" +
            ",CI0,123,2000-09-09,2)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("HU-P4", "Jorge", "Luis", "Quispe", "", "P1234567", "70022222", "1900-01-01", "3", null, DisplayName="Crear huésped (Insert) - datos pairwise(HU-P4,Jorge,Luis,Quispe,,P1234567,7002222" +
            "2,1900-01-01,3)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("HU-P5", "A", "", "Quispe", "Salazar", "CI200003", "70033333", "1998-11-02", "4", null, DisplayName="Crear huésped (Insert) - datos pairwise(HU-P5,A,,Quispe,Salazar,CI200003,70033333" +
            ",1998-11-02,4)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("HU-P6", "NombreMuyLargoExceso", "Luis", "Quispe", "Flores", "CI200005", "70055555", "1980-01-15", "5", null, DisplayName="Crear huésped (Insert) - datos pairwise(HU-P6,NombreMuyLargoExceso,Luis,Quispe,Fl" +
            "ores,CI200005,70055555,1980-01-15,5)")]
        public async global::System.Threading.Tasks.Task CrearHuespedInsert_DatosPairwise(string tC_ID, string primerNombre, string segundoNombre, string primerApellido, string segundoApellido, string documento, string telefono, string fechaNac, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ui",
                    "huesped",
                    "insert",
                    "pairwise"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("TC_ID", tC_ID);
            argumentsOfScenario.Add("PrimerNombre", primerNombre);
            argumentsOfScenario.Add("SegundoNombre", segundoNombre);
            argumentsOfScenario.Add("PrimerApellido", primerApellido);
            argumentsOfScenario.Add("SegundoApellido", segundoApellido);
            argumentsOfScenario.Add("Documento", documento);
            argumentsOfScenario.Add("Telefono", telefono);
            argumentsOfScenario.Add("FechaNac", fechaNac);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Crear huésped (Insert) - datos pairwise", @"    Dado que navego a la página de huéspedes
    Cuando ingreso el primer nombre ""<PrimerNombre>""
    Y ingreso el segundo nombre ""<SegundoNombre>""
    Y ingreso el primer apellido ""<PrimerApellido>""
    Y ingreso el segundo apellido ""<SegundoApellido>""
    Y ingreso el documento ""<Documento>""
    Y ingreso el teléfono ""<Telefono>""
    Y ingreso la fecha de nacimiento ""<FechaNac>""
    Y hago click en guardar huésped
    Entonces debería ver un mensaje de éxito
    Y debería ver el ID del huésped creado", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Actualizar huésped (Update) - datos pairwise")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Actualizar huésped (Update) - datos pairwise")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Huéspedes UI")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ui")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("huesped")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("update")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("pairwise")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("CI200001", "999888777", "nuevo@example.com", "6", null, DisplayName="Actualizar huésped (Update) - datos pairwise(CI200001,999888777,nuevo@example.com" +
            ",6)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("P1234567", "", "invalid@", "7", null, DisplayName="Actualizar huésped (Update) - datos pairwise(P1234567,,invalid@,7)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("CI0", "1234567890", "contacto@dominio.com", "8", null, DisplayName="Actualizar huésped (Update) - datos pairwise(CI0,1234567890,contacto@dominio.com," +
            "8)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DataRowAttribute("CI200003", "70033333", "nuevo@example.com", "9", null, DisplayName="Actualizar huésped (Update) - datos pairwise(CI200003,70033333,nuevo@example.com," +
            "9)")]
        public async global::System.Threading.Tasks.Task ActualizarHuespedUpdate_DatosPairwise(string numDocBusqueda, string nuevoTelefono, string nuevoEmail, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ui",
                    "huesped",
                    "update",
                    "pairwise"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("NumDocBusqueda", numDocBusqueda);
            argumentsOfScenario.Add("NuevoTelefono", nuevoTelefono);
            argumentsOfScenario.Add("NuevoEmail", nuevoEmail);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Actualizar huésped (Update) - datos pairwise", @"    Dado que navego a la página de huéspedes
    Y busco el huésped con documento ""<NumDocBusqueda>""
    Y hago click en editar huésped
    Y modifico el teléfono a ""<NuevoTelefono>""
    Y modifico el correo a ""<NuevoEmail>""
    Y hago click en guardar cambios
    Entonces debería ver un mensaje de éxito
    Y debería ver el teléfono actualizado para el huésped", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 34
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Eliminar huésped existente (Happy Path)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Eliminar huésped existente (Happy Path)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Huéspedes UI")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ui")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("huesped")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("delete")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("happy-path")]
        public async global::System.Threading.Tasks.Task EliminarHuespedExistenteHappyPath()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "huesped",
                    "delete",
                    "happy-path"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Eliminar huésped existente (Happy Path)", @"    Dado que navego a la página de huéspedes
    Cuando busco el huésped con documento ""CI200001""
    Y hago click en eliminar huésped
    Y confirmo la eliminación
    Entonces debería ver un mensaje de confirmación de eliminación
    Y el huésped ya no debería aparecer en la lista", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 52
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute("Buscar/Seleccionar huésped (Happy Path)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Buscar/Seleccionar huésped (Happy Path)")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Huéspedes UI")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ui")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("huesped")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("select")]
        [global::Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("happy-path")]
        public async global::System.Threading.Tasks.Task BuscarSeleccionarHuespedHappyPath()
        {
            string[] tagsOfScenario = new string[] {
                    "ui",
                    "huesped",
                    "select",
                    "happy-path"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Buscar/Seleccionar huésped (Happy Path)", "    Dado que navego a la página de huéspedes\r\n    Cuando busco el huésped con doc" +
                    "umento \"CI200001\"\r\n    Entonces debería ver el huésped en la lista", tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 61
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
